from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import io

class ReportService:
    @staticmethod
    def generate_property_report(analysis):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#ff9f43"),
            alignment=1,
            spaceAfter=20
        )
        
        heading_style = ParagraphStyle(
            'HeadingStyle',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor("#333333"),
            spaceBefore=15,
            spaceAfter=10
        )
        
        body_style = styles['BodyText']
        
        features = []
        
        # Title
        features.append(Paragraph("Climate Risk Analysis Report", title_style))
        features.append(Spacer(1, 12))
        
        # Property details
        features.append(Paragraph("Property Details", heading_style))
        data = [
            ["Property Name", analysis.property_name],
            ["Address", analysis.address],
            ["Asset Value", f"Rs. {analysis.asset_value:,.2f}"],
            ["Loan Term", f"{analysis.loan_term} years"]
        ]
        t = Table(data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        features.append(t)
        
        # Climate score
        features.append(Paragraph("Climate Credit Score", heading_style))
        features.append(Paragraph(f"Overall Score: <b>{analysis.climate_score}/100</b>", body_style))
        features.append(Paragraph(f"Risk Level: {analysis.risk_level}", body_style))
        
        # AI Explanation
        features.append(Paragraph("AI Explanation", heading_style))
        features.append(Paragraph(analysis.ai_insights or "No explanation available.", body_style))
        
        # Risk Factors
        features.append(Paragraph("Risk Factors Breakdown", heading_style))
        risks = analysis.risk_factors or {}
        risk_data = [["Factor", "Risk Level (0-100)"]]
        for factor, val in risks.items():
            risk_data.append([factor.capitalize(), f"{val}%"])
        
        rt = Table(risk_data, colWidths=[150, 150])
        rt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#ff9f43")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        features.append(rt)
        
        # Recommendation
        features.append(Paragraph("Loan Recommendation", heading_style))
        rec = analysis.loan_recommendation or {}
        if isinstance(rec, dict):
            features.append(Paragraph(f"Adjustment: {rec.get('recommended_interest_adjustment', 0):+.2f}%", body_style))
            features.append(Paragraph(rec.get('recommendation_text', ''), body_style))
        else:
            features.append(Paragraph(str(rec), body_style))

        # Footer
        features.append(Spacer(1, 40))
        features.append(Paragraph("Generated by Climate Credit Score Engine AI", styles['Italic']))
        
        doc.build(features)
        buffer.seek(0)
        return buffer

    @staticmethod
    def generate_portfolio_report(properties, stats):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#ff9f43"),
            alignment=1,
            spaceAfter=20
        )
        
        heading_style = ParagraphStyle(
            'HeadingStyle',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor("#333333"),
            spaceBefore=15,
            spaceAfter=10
        )
        
        body_style = styles['BodyText']
        
        features = []
        
        # Title
        features.append(Paragraph("Portfolio Climate Risk Analysis", title_style))
        features.append(Spacer(1, 12))
        
        # Dashboard Summary
        features.append(Paragraph("Portfolio Overview", heading_style))
        summary_data = [
            ["Total Assets", str(len(properties))],
            ["Portfolio Score", str(stats.get('avg_score', 0))],
            ["Total Asset Value", f"Rs. {stats.get('total_value', 0):,.2f}"],
            ["High Risk Assets", str(stats.get('high_risk', 0))],
            ["Medium Risk Assets", str(stats.get('med_risk', 0))],
            ["Low Risk Assets", str(stats.get('low_risk', 0))]
        ]
        
        st = Table(summary_data, colWidths=[150, 300])
        st.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.whitesmoke),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        features.append(st)
        features.append(Spacer(1, 20))
        
        # Asset Breakdown
        features.append(Paragraph("Asset Inventory", heading_style))
        
        # Table Header
        asset_data = [["Property", "Value (Rs.)", "Credit Score", "Risk Level"]]
        
        for p in properties:
            name = p.property_name or p.address or "Unknown"
            # Format nicely
            asset_data.append([
                Paragraph(name, body_style),
                f"{p.asset_value:,.2f}",
                str(p.climate_score),
                p.risk_level
            ])
            
        at = Table(asset_data, colWidths=[200, 100, 80, 70])
        at.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#ff9f43")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        
        features.append(at)
        
        # Footer
        features.append(Spacer(1, 40))
        features.append(Paragraph("Generated by Climate Credit Score Engine AI", styles['Italic']))
        
        doc.build(features)
        buffer.seek(0)
        return buffer
